[package]
name = "ria-greplite"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "ria-grep"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.13"
regex = "1.5.4"
